//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Удовл кл.
    /// </summary>
    // *** Start programmer edit section *** (УдовлКл CustomAttributes)

    // *** End programmer edit section *** (УдовлКл CustomAttributes)
    public enum УдовлКл
    {
        
        // *** Start programmer edit section *** (УдовлКл.Удовл CustomAttributes)

        // *** End programmer edit section *** (УдовлКл.Удовл CustomAttributes)
        Удовл,
        
        // *** Start programmer edit section *** (УдовлКл.НеУдовл CustomAttributes)

        // *** End programmer edit section *** (УдовлКл.НеУдовл CustomAttributes)
        НеУдовл,
    }
}
