//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Формир рез пос.
    /// </summary>
    // *** Start programmer edit section *** (ФормирРезПос CustomAttributes)

    // *** End programmer edit section *** (ФормирРезПос CustomAttributes)
    [AutoAltered()]
    [Caption("Формир рез пос")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ФормирРезПосE", new string[] {
            "Дата as \'Дата\'",
            "ФормирРаспред.НомерДокРаспр",
            "ФормирРаспред.ДокумПостав.Организация.Наименование",
            "ФормирРаспред.ДокумПостав.Клиенты.НаимЗаказ",
            "ФормирРаспред.ДокумПостав.Клиенты.Телефон",
            "ФормирРаспред.ПунктПогрузки.Наименование",
            "ФормирРаспред.ДокумПостав.Клиенты.АдресПостав",
            "СтатусЗаказа",
            "НаличиеДеф",
            "УдовлКл"})]
    [View("ФормирРезПосL", new string[] {
            "Дата as \'Дата\'",
            "СтатусЗаказа as \'Статус заказа\'",
            "НаличиеДеф as \'Наличие деф\'",
            "УдовлКл as \'Удовл кл\'",
            "ФормирРаспред.НомерДокРаспр as \'Номер док распр\'"})]
    public class ФормирРезПос : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private IIS.Proekt.СтатусЗаказа fСтатусЗаказа;
        
        private bool fНаличиеДеф;
        
        private IIS.Proekt.УдовлКл fУдовлКл;
        
        private IIS.Proekt.ФормирРаспред fФормирРаспред;
        
        // *** Start programmer edit section *** (ФормирРезПос CustomMembers)

        // *** End programmer edit section *** (ФормирРезПос CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРезПос.Дата CustomAttributes)

        // *** End programmer edit section *** (ФормирРезПос.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРезПос.Дата Get start)

                // *** End programmer edit section *** (ФормирРезПос.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ФормирРезПос.Дата Get end)

                // *** End programmer edit section *** (ФормирРезПос.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРезПос.Дата Set start)

                // *** End programmer edit section *** (ФормирРезПос.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ФормирРезПос.Дата Set end)

                // *** End programmer edit section *** (ФормирРезПос.Дата Set end)
            }
        }
        
        /// <summary>
        /// НаличиеДеф.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРезПос.НаличиеДеф CustomAttributes)

        // *** End programmer edit section *** (ФормирРезПос.НаличиеДеф CustomAttributes)
        public virtual bool НаличиеДеф
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРезПос.НаличиеДеф Get start)

                // *** End programmer edit section *** (ФормирРезПос.НаличиеДеф Get start)
                bool result = this.fНаличиеДеф;
                // *** Start programmer edit section *** (ФормирРезПос.НаличиеДеф Get end)

                // *** End programmer edit section *** (ФормирРезПос.НаличиеДеф Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРезПос.НаличиеДеф Set start)

                // *** End programmer edit section *** (ФормирРезПос.НаличиеДеф Set start)
                this.fНаличиеДеф = value;
                // *** Start programmer edit section *** (ФормирРезПос.НаличиеДеф Set end)

                // *** End programmer edit section *** (ФормирРезПос.НаличиеДеф Set end)
            }
        }
        
        /// <summary>
        /// СтатусЗаказа.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРезПос.СтатусЗаказа CustomAttributes)

        // *** End programmer edit section *** (ФормирРезПос.СтатусЗаказа CustomAttributes)
        public virtual IIS.Proekt.СтатусЗаказа СтатусЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРезПос.СтатусЗаказа Get start)

                // *** End programmer edit section *** (ФормирРезПос.СтатусЗаказа Get start)
                IIS.Proekt.СтатусЗаказа result = this.fСтатусЗаказа;
                // *** Start programmer edit section *** (ФормирРезПос.СтатусЗаказа Get end)

                // *** End programmer edit section *** (ФормирРезПос.СтатусЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРезПос.СтатусЗаказа Set start)

                // *** End programmer edit section *** (ФормирРезПос.СтатусЗаказа Set start)
                this.fСтатусЗаказа = value;
                // *** Start programmer edit section *** (ФормирРезПос.СтатусЗаказа Set end)

                // *** End programmer edit section *** (ФормирРезПос.СтатусЗаказа Set end)
            }
        }
        
        /// <summary>
        /// УдовлКл.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРезПос.УдовлКл CustomAttributes)

        // *** End programmer edit section *** (ФормирРезПос.УдовлКл CustomAttributes)
        public virtual IIS.Proekt.УдовлКл УдовлКл
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРезПос.УдовлКл Get start)

                // *** End programmer edit section *** (ФормирРезПос.УдовлКл Get start)
                IIS.Proekt.УдовлКл result = this.fУдовлКл;
                // *** Start programmer edit section *** (ФормирРезПос.УдовлКл Get end)

                // *** End programmer edit section *** (ФормирРезПос.УдовлКл Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРезПос.УдовлКл Set start)

                // *** End programmer edit section *** (ФормирРезПос.УдовлКл Set start)
                this.fУдовлКл = value;
                // *** Start programmer edit section *** (ФормирРезПос.УдовлКл Set end)

                // *** End programmer edit section *** (ФормирРезПос.УдовлКл Set end)
            }
        }
        
        /// <summary>
        /// Формир рез пос.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРезПос.ФормирРаспред CustomAttributes)

        // *** End programmer edit section *** (ФормирРезПос.ФормирРаспред CustomAttributes)
        [PropertyStorage(new string[] {
                "ФормирРаспред"})]
        [NotNull()]
        public virtual IIS.Proekt.ФормирРаспред ФормирРаспред
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРезПос.ФормирРаспред Get start)

                // *** End programmer edit section *** (ФормирРезПос.ФормирРаспред Get start)
                IIS.Proekt.ФормирРаспред result = this.fФормирРаспред;
                // *** Start programmer edit section *** (ФормирРезПос.ФормирРаспред Get end)

                // *** End programmer edit section *** (ФормирРезПос.ФормирРаспред Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРезПос.ФормирРаспред Set start)

                // *** End programmer edit section *** (ФормирРезПос.ФормирРаспред Set start)
                this.fФормирРаспред = value;
                // *** Start programmer edit section *** (ФормирРезПос.ФормирРаспред Set end)

                // *** End programmer edit section *** (ФормирРезПос.ФормирРаспред Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ФормирРезПосE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФормирРезПосE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФормирРезПосE", typeof(IIS.Proekt.ФормирРезПос));
                }
            }
            
            /// <summary>
            /// "ФормирРезПосL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФормирРезПосL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФормирРезПосL", typeof(IIS.Proekt.ФормирРезПос));
                }
            }
        }
    }
}
